# Generated by Django 5.1.6 on 2025-03-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget_range',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
