# Generated by Django 5.1.6 on 2025-03-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trip_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('monsoon', 'Monsoon')], default='Any', max_length=20),
        ),
    ]
