# Generated by Django 5.0.4 on 2025-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_trip_budget_range_alter_trip_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='budget_range',
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
