# Generated by Django 5.1.6 on 2025-03-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_rename_booking_date_booking_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
