# Generated by Django 5.1.6 on 2025-03-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
