# Generated by Django 5.1.6 on 2025-03-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_trip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
