# Generated by Django 5.1.6 on 2025-03-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_booking_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(),
        ),
    ]
